name: Prepare Release
on:
  workflow_dispatch:

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: run prepare
        env:
          PAT_GITHUB: ${{secrets.PAT_GITHUB}}
        run: make release
