name: Publish Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT_GITHUB}}

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: prepare
        run: make prepare

      - name: run prepare
        env:
          PAT_GITHUB: ${{secrets.PAT_GITHUB}}
        run: ./scripts/release.sh publish
